pdf:
	pdflatex proj5.tex
	pdflatex proj5.tex
clean:
	-rm -f proj5.aux fsm-eps-converted-to.pdf proj5.nav proj5.snm proj5.toc proj5.log proj5.out texput.log proj5.pdf
pack:
	zip xvojan00-fit.zip citac_moore.png fsm.eps Makefile proj5.tex
